version: '3.2'
volumes:
  app:

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    working_dir: /var/www
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    volumes:
    - /etc/passwd:/etc/passwd:ro
    - /etc/group:/etc/group:ro
    - ./:/var/www
    command: keep-alive.sh
